# Generated by Django 3.2.8 on 2021-10-31 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0002_eventtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='format: required', max_length=50, verbose_name='service name')),
                ('description', models.TextField(help_text='format: required', verbose_name='service description')),
            ],
            options={
                'verbose_name': 'Service type',
                'verbose_name_plural': 'Service types',
            },
        ),
    ]
