# Generated by Django 3.2.8 on 2021-11-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='name',
            field=models.CharField(help_text='format: required', max_length=50, unique=True, verbose_name='business name'),
        ),
    ]
