# Generated by Django 3.2.8 on 2021-10-31 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0003_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Neighbourhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='format: required', max_length=50, verbose_name='neighbourhood name')),
                ('slogan', models.CharField(help_text='format: required, max_length=50', max_length=50, verbose_name='slogan')),
                ('police_hotline', models.CharField(help_text='format: required', max_length=10, verbose_name='police hotline')),
                ('hospital_hotline', models.CharField(help_text='format: required', max_length=10, verbose_name='hospital hotline')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='neighbourhood', to='neighbourhood.location')),
            ],
        ),
    ]
