# Generated by Django 3.2.8 on 2021-11-03 02:16

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0004_alter_occurrence_to_happen_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='images/'),
        ),
        migrations.AlterField(
            model_name='neighbourhood',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='images/'),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='image_description',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='images/'),
        ),
    ]
