# Generated by Django 3.2.8 on 2021-11-05 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0005_auto_20211103_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbourhood',
            name='hospital_hotline',
            field=models.CharField(help_text='format: required', max_length=100, verbose_name='hospital hotline'),
        ),
        migrations.AlterField(
            model_name='neighbourhood',
            name='police_hotline',
            field=models.CharField(help_text='format: required', max_length=100, verbose_name='police hotline'),
        ),
    ]
